// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrM1R5x6TZr5uLjaFwB-j1bRxEJvYivig',
    appId: '1:609476139291:web:2841e5736f16f00fe7dbbe',
    messagingSenderId: '609476139291',
    projectId: 'myfriends-app-b016e',
    authDomain: 'myfriends-app-b016e.firebaseapp.com',
    storageBucket: 'myfriends-app-b016e.firebasestorage.app',
    measurementId: 'G-ND1MXVXT0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz9LmpOsnSFvOlQl08MtrrBBuSgAMplhA',
    appId: '1:609476139291:android:9acd2c02cc52cb41e7dbbe',
    messagingSenderId: '609476139291',
    projectId: 'myfriends-app-b016e',
    storageBucket: 'myfriends-app-b016e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHus3J9EPF4CW7ehRoeww5iX1QUMPRCOY',
    appId: '1:609476139291:ios:f1db03dab5dce4a1e7dbbe',
    messagingSenderId: '609476139291',
    projectId: 'myfriends-app-b016e',
    storageBucket: 'myfriends-app-b016e.firebasestorage.app',
    iosBundleId: 'com.example.myfriendsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHus3J9EPF4CW7ehRoeww5iX1QUMPRCOY',
    appId: '1:609476139291:ios:f1db03dab5dce4a1e7dbbe',
    messagingSenderId: '609476139291',
    projectId: 'myfriends-app-b016e',
    storageBucket: 'myfriends-app-b016e.firebasestorage.app',
    iosBundleId: 'com.example.myfriendsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrM1R5x6TZr5uLjaFwB-j1bRxEJvYivig',
    appId: '1:609476139291:web:e1b203f0543e9c2fe7dbbe',
    messagingSenderId: '609476139291',
    projectId: 'myfriends-app-b016e',
    authDomain: 'myfriends-app-b016e.firebaseapp.com',
    storageBucket: 'myfriends-app-b016e.firebasestorage.app',
    measurementId: 'G-JT9F30M804',
  );

}